Hw13
Ayupov-Ayaz/otus-hw-test pull request #18
Opened 2023-05-28 07:15 UTC by Ayupov-Ayaz

2023-05-28 15:10 UTC, dshemin requested changes

2023-05-28 15:10 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	protoc --proto_path=internal/server/grpc/proto/ \
Критично:

> добавить в Makefile команду `generate`; `make generate` - вызывает `go generate`, которая в свою очередь
генерирует код GRPC сервера на основе Protobuf спецификаций;

2023-05-28 15:10 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/internal/configs/grpc/grpc.go
> +func (c Config) Addr() string {
Важно:

Для этого существует: https://pkg.go.dev/net#JoinHostPort которая будет работать корректно во всех случаях. Ваш же код, упадёт если кто-то в конфиге передаст IPv6 адрес

2023-05-28 15:10 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if err := e.validator.Validate(ctx, event); err != nil {
Важно:

Валидатор опционален так, как передаётся через `WithValidator`. что будет если я забуду его передать? Тоже самое и про логер.

Шаблон, который вы использовали, подходит для ситуаций когда у нас есть некий процесс, который в зависимости от внешних настроек должен себя вести по разному. У нас такого нет. И применять его - не надо.

2023-05-28 15:10 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/api/event_handler.go
> +func (e *EventHandler) mustEmbedUnimplementedEventServiceServer() {}
Важно:

для этого генерируется специальный тип, которую можно встроить в наш хендлер и не писать этого руками.

2023-05-28 15:10 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/event/mysql/storage.go
> +	createQuery = "INSERT INTO events " +
Важно:

Не самое удачное решение - прыгать между строками в коде ради того чтобы почитать какой запрос делается.

2023-05-28 15:10 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/event/mysql/storage.go
> +	createQuery = "INSERT INTO events " +
Важно:

Для многострочных строковых констант и переменных можно использовать символ `

https://go.dev/ref/spec#String_literals

2023-05-29 02:20 UTC, Ayupov-Ayaz commented on hw12_13_14_15_calendar/Makefile
> +	protoc --proto_path=internal/server/grpc/proto/ \
исправил

2023-05-29 02:21 UTC, Ayupov-Ayaz commented on hw12_13_14_15_calendar/cmd/calendar/internal/configs/grpc/grpc.go
> +func (c Config) Addr() string {
исправил

2023-05-29 02:23 UTC, Ayupov-Ayaz commented on hw12_13_14_15_calendar/internal/app/app.go
> +	if err := e.validator.Validate(ctx, event); err != nil {
исправил

2023-05-29 02:29 UTC, Ayupov-Ayaz commented on hw12_13_14_15_calendar/internal/server/grpc/api/event_handler.go
> +func (e *EventHandler) mustEmbedUnimplementedEventServiceServer() {}
понял, не знал, спасибо; 
Исправил

2023-05-29 02:36 UTC, Ayupov-Ayaz commented on hw12_13_14_15_calendar/internal/storage/event/mysql/storage.go
> +	createQuery = "INSERT INTO events " +
исправил

2023-05-30 02:45 UTC, closed without merging